src/index.ts, src/types.ts, test/defaults.test.ts, test/request.test.ts
This adds a timeZone option to the Octokit constructor. The value provided is set as the time-zone header in the client defaults, so all requests made with that octokit instance will have that time-zone header.
I added test cases for this in `defaults.test.ts` and `request.test.ts`.
This is pretty similar to https://github.com/octokit/rest.js/pull/1498, but if anything in this PR isn't as idiomatic to this repo I'm happy to make changes!
=> Add timezone option to Octokit constructor

README.md, src/index.ts, src/types.ts, test/__snapshots__/plugin.test.ts.snap, test/plugin.test.ts
From the ideas that have been thrown out there to solve the issue described in #51, this is my favorite.
Instead of `.plugin(arrayOfPlugins[])`, which could lead to a type-widening error, this PR moves to use `.plugin(plugin1, plugin2, plugin3, etc...)`, where each plugin is hardcoded into the type-system
Why this approach?
I think this will be easiest on plugin authors, who don't have to change anything with how they currently develop plugins - such as having to worry about whether they need to return an object, if they return void, etc.
This will also be an easy fix for users of Octokit. `.plugin([paginateRest, queueWorker, logService])` becomes `.plugin(paginateRest, queueWorker, logService)`
**TODOs**
Example warning when using old syntax:
Fixes #51
=> fix: Fixes type-widening bug when handling plugins.

README.md
=> docs(README): `plugin-throttle` should be `plugin-throttling`, `plugin-paginate` should be `plugin-paginate-rest`

src/types.ts
This PRs adds types for the options specified in the [rest.js docs](https://octokit.github.io/rest.js/v18#usage)
**Before:**
**After:**
=> Add missing types for `OctokitOptions`

CONTRIBUTING.md, test/issues.test.ts
Figuring out where to put a test to reproduce a bug report is unnecessary friction, especially to new contributors. Instead let us use this "catch-all" test file for all issues, so there is one thing less new contributors need to worry about. With every breaking release, or whenever someone feels like it, the tests can be moved into the appropriate places or removed entirely if they are no longer necessary.
=> test: add `issues.test.ts` as a place to put tests if it is unclear where else to put them

src/index.ts, test/auth.test.ts
=> fix: use correct URL to create installation access token for `octokit.graphql()` and GHES

src/index.ts, test/auth.test.ts
unblocks probot/octokit-auth-probot#1
=> feat(auth): pass `octokit` and `octokitOptions` to `options.authStrategy`

package-lock.json, package.json, src/index.ts, src/types.ts, test/constructor.test.ts, test/hook.test.ts
Shout out to @MunifTanjim who made this possible via https://github.com/gr2m/before-after-hook/pull/81
=> feat(typescript): types for `octokit.hook.{before,after,error,wrap}("request", () => {})` methods

src/index.ts
Before any property on an `octokit` instance could be used without complaint at build time. With this change, all additional properties on an `octokit` instance need to be added explicitly using plugins
=> fix(typescript): remove `[key: string]: any` from `Octokit` class

.github/workflows/test.yml, package.json, src/index.ts, test/typescript-validate.ts
implements changes suggested by @Andarist at https://github.com/gr2m/javascript-plugin-architecture-with-typescript-definitions/issues/31
=> feat(typescript): do not permit unknown keys on `octokit` instance'

README.md, package-lock.json, package.json
- docs(README): `error.headers.etag` -> `error.response.headers.etag`
- fix(deps): bump `@ocotkit/request` to `^5.6.0`
- build(package): lock file
=> feat: `error.response`

src/types.ts, test/typescript-validate.ts
prevents the `octokit` instance from becoming an intersection with `void`, see https://github.com/octokit/octokit.js/issues/2115
=> fix(typescript): avoid the `void`

src/types.ts
=> feat(types): convert type 'OctokitOptions' to interface

README.md
According to the expected result in the comment in the example, this property should be named `opt1`.
=> docs(README): fix example

package-lock.json, package.json
Fixes #575 and reverts the breaking dependency changes that prematurely dropped support for Node 14/16.
=> fix(deps): revert breaking dependency changes

package-lock.json, package.json, test/agent-ca/agent-ca-test.test.ts
RE: https://github.com/octokit/core.js/pull/563
Now that we have introduced the changes for removing agent from octokit.request we needed to rework some tests to use the new patterns.  
----
* The CA tests were skipped
* They have now been rewritten to use a dispatcher and custom fetch
=> Rewrites the ca tests to use the dispatcher and custom fetch

test/agent-ca/agent-ca-test.test.ts, test/agent-proxy/agent-proxy-test.test.ts
- refactor(agent-ca-test): improve types
- test(agent-proxy): restore test coverage with undici
Resolves #586 
----
* Tests for `agent-proxy` were skipped
* Tests for `agent-proxy` are restored using `undici`
* https://undici.nodejs.org/
----
Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!
If `Yes`, what's the impact:
* N/A
`Type: Maintenance`
----
=> test(agent-proxy): restore test coverage with `undici`

test/log.test.ts
@gr2m 
@wolfy1339 
As requested here the "fixed" unit test. Because I bind the console methods very early, I needed to change the tests.
---
-
-
---
=> fix: follow up hotpath test

package.json, scripts/build.mjs, src/index.ts, src/types.ts, test/agent-ca/agent-ca-test.test.ts, test/agent-proxy/agent-proxy-test.test.ts, test/auth.test.ts, test/constructor.test.ts, test/defaults.test.ts, test/graphql.test.ts, test/hook.test.ts, test/issues.test.ts, test/log.test.ts, test/plugin.test.ts, test/request.test.ts, test/smoke.test.ts, test/tsconfig.test.json, test/typescript-validate.ts
This PR replaces NodeJS internal module imports with `node:` specifier imports.
=> refactor: use `node:` specifier imports and full relative path imports

README.md, package-lock.json, package.json, scripts/build.mjs, src/index.ts, test/agent-ca/agent-ca-test.test.ts, test/agent-proxy/agent-proxy-test.test.ts, test/auth.test.ts, test/log.test.ts, test/request.test.ts, test/tsconfig.test.json
BREAKING CHANGE: package is now ESM
=> feat: package is now ESM

scripts/build.mjs
Now that the package is ESM, `eslint` may return the following errors:
```
error  Unable to resolve path to module '@octokit/core'  import/no-unresolved
error  "@octokit/core" is not found                      node/no-missing-import
```
eslint should no longer report the errors
---
=> fix(pkg): add main entry point 

README.md, scripts/build.mjs, src/index.ts
Resolves #667 
Resolves #665
Partly reverts #662
---
- Some consumers of this package could not resolve it properly (ex: `jest`, `ts-node`, `tsx`)
- CJS consumers would be getting errors even though the package is ESM
- Consumers cannot import paths from the package like in CJS
- Clients should be able to import the module without any errors with the fallback
- CJS consumers will generate a better error with the new fallback
- Consumers are able to import types from the `dist-types/types.d.ts` file in the package
---
=> fix(pkg): add `default` fallback and `types` export

test/tsconfig.test.json
After the migration to `vitest`, it is not necessary anymore to have a custom `tsconfig.json`
---
- We have an unused file in the codebase: `tsconfig.test.json`
- Same behavior but with unused file removed.
---
=> chore(test): remove unused `tsconfig.test.json`

package-lock.json, package.json
See https://github.com/octokit/octokit.js/issues/2762#issuecomment-2486997620
----
* Types would include a reference to `@types/node` even though there is nothing using Node specific APIs in the types
* Update `@octokit/types` to make sure types are platform agnostic
* Update all Octokit types to the version that includes the fixed types
----
=> fix(deps): bump Octokit dependencies to fix Deno compat

.github/workflows/update-prettier.yml
---
- Used Node 16 for the `update-prettier` workflow
- Use Node LTS instead of pinning to a specific version
---
=> ci(prettier): use Node LTS instead of Node v16
