package-lock.json, package.json, src/index.ts, src/types.ts
https://github.com/octokit/types.ts/pull/1
=> feat: improve TypeScript definitions via @octokit/types

package-lock.json, package.json, src/index.ts, test/smoke.test.ts
=> Octokit.VERSION

README.md
=> `timeZone` option

package-lock.json, src/index.ts, test/auth.test.ts
This makes sure that requests sent within `octokit.auth()` use `octokit.request`
=> set `options.request` when custom authStrategy is set

package-lock.json, package.json
=> feat(TypeScript): types for all known types

package-lock.json, src/index.ts, test/graphql.test.ts
=> fix: send GraphQL requests to the correct URL for GitHub Enterprise Server

README.md, src/index.ts, test/defaults.test.ts
=> feat: `Octokit.defaults()` accepts callback function

src/index.ts
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/octokit-core.js/commit/fc7a00ceaeb78cd08a992bf6a75c66a61f52ca33#commitcomment-41652799
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/octokit-core.js/commit/e066fdefa48fdd93634d88fe24e83457796925c3
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.
=> chore: spelling: registered

package-lock.json, src/index.ts, test/auth.test.ts
Closes #218
I reworked the runkit example to use fetch-mock and then added it to `auth.test.ts`, I also had to force an update of `@octokit/auth` to pull in the changes in `@octokit/auth-app`
=> fix: pass through logger to @octokit/auth-app

test/graphql.test.ts
adding test for setting custom headers with GraphQL queries
=> test(graphql): custom headers

README.md
Not sure which version this was changed to a named export.
=> docs: fix @octokit/action-auth

.github/ISSUE_TEMPLATE/config.yml
follow up to https://github.com/octokit/auth-oauth-user.js/pull/85
=> docs(ISSUE_TEMPLATE): fix help link

.github/pull_request_template.md, .github/workflows/codeql.yml, .github/workflows/release.yml, .github/workflows/test.yml, README.md, package.json
This changes the default branch from master --> main across the repository content to match the state of the repository settings. 
----
* Links, Actions, and references used the "master" default branch name. 
* Links, Actions, and references use the "main" default branch name
If `Yes`, what's the impact:  
* N/A
Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`
----
=> Default branch rename

README.md
addresses https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/668
----
n/a
n/a
----
=> docs(README): add note to plugins about adding methods directly to `octokit` instance

package-lock.json, package.json
----
* Used a custom fork of `fetch-mock` for Fetch API support
* Use the `fetch-mock` module again, it has been updated to support the Fetch API
----
=> build(deps): replace `@gr2m/fetch-mock` with `fetch-mock`

package-lock.json, package.json
Relates to https://github.com/octokit/tsconfig/issues/29#issuecomment-2372295972
----
* We were testing types without `--exactOptionalPropertyTypes` option
* We start testing types with `--exactOptionalPropertyTypes` option
----
=> test(types): add --exactOptionalPropertyTypes option

package-lock.json, package.json
=> chore(deps): remove unused dependency @types/jest

package-lock.json, package.json
=> fix(deps): bump Octokit dependencies vulnerable to ReDos

package-lock.json, package.json, scripts/build.mjs
=> build: remove glob

src/index.ts
=> fix: add createLogger to ensure that pino does not break
